  file_reader_task:
    description: >
      Read the uploaded file and extract its content so it can be passed to the explainer.
    expected_output: >
      The raw code text extracted from the uploaded file.
    
    agent: file_reader


  explainer_task:
    description: >
      You will be given a code snippet {code_snippet}. Identify the programming language first. 
      Then summarize the code in simple, beginner-friendly terms. Focus on the core logic, avoid excessive detail, 
      and ensure the summary is concise and accurate.
      
    expected_output: >
      A short, accurate explanation of the code snippet, including what it does, its main structure, and key points. 
      Do not add unrelated content or guesses about frameworks if not explicitly used.
    
    agent: explainer
